# flake-parts/features/home/cli/file-managers/yazi.nix
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.cli-environment;
in
{
  config = lib.mkIf cfg.enable {
    programs.yazi = {
      enable = true;
      enableZshIntegration = true;

      settings = {
        manager = {
          show_hidden = true;
          sort_by = "natural";
          sort_dir_first = true;
        };
        opener = {
          edit = [
            {
              run = ''${pkgs.helix}/bin/hx "$@"'';
              block = true;
            }
          ];
        };
      };

      # Yazi theme is applied via theme.toml generated by matugen

      keymap = {
        manager.prepend_keymap = [
          {
            on = [ "e" ];
            run = "open";
            desc = "Open with Helix";
          }
          {
            on = [ "<C-s>" ];
            run = "escape";
            desc = "Exit yazi";
          }
        ];
      };
    };
  };
}
