# Hardware Configuration Placeholder
#
# This file should be generated by nixos-generate-config:
#   nixos-generate-config --root /mnt --show-hardware-config > hardware-configuration.nix
#
# Or use clan's facter for automatic hardware detection:
#   clan facts generate <machine-name>
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  nixpkgs.hostPlatform = "x86_64-linux";
}
