{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  cfg = config.layers.layer-50.cli;
  nixvimEnabled = config.layers.layer-50.cli.nixvim.enable or false;
  editorBin = if nixvimEnabled then "nvim" else "${lib.getExe pkgs.neovim}";

  yazelixOrchestrator = pkgs.yazelix-orchestrator or null;
  yazelixPopup = pkgs.yazelix-popup-runner or null;

  zjstatusWasm = "${
    inputs.zjstatus.packages.${pkgs.stdenv.hostPlatform.system}.default
  }/bin/zjstatus.wasm";

  # ── Clipboard Bridge (Wayland + X11 + OSC 52) ────────────────────────
  # Zellij's background server often lacks $WAYLAND_DISPLAY, causing
  # wl-copy to silently fail. This wrapper tries every available path.
  zellij-clipboard = pkgs.writeShellScriptBin "zellij-clipboard" ''
    set -e

    # Try to locate the Wayland display
    if [ -z "''${WAYLAND_DISPLAY:-}" ]; then
      for sock in "$XDG_RUNTIME_DIR/wayland-0" "$XDG_RUNTIME_DIR/wayland-1"; do
        if [ -S "$sock" ]; then
          export WAYLAND_DISPLAY="''${sock##*/}"
          break
        fi
      done
    fi

    # 1) Wayland → wl-copy (preferred)
    if [ -n "''${WAYLAND_DISPLAY:-}" ] && command -v wl-copy >/dev/null 2>&1; then
      exec wl-copy --paste-once "$@"
    fi

    # 2) X11 → xclip
    if [ -n "''${DISPLAY:-}" ] && command -v xclip >/dev/null 2>&1; then
      exec xclip -selection clipboard -i "$@"
    fi

    # 3) OSC 52 fallback → tell terminal to copy
    if command -v base64 >/dev/null 2>&1; then
      INPUT=$(cat)
      ESCAPED=$(printf "%s" "$INPUT" | base64 | tr -d '\n')
      printf "\e]52;c;%s\a" "$ESCAPED"
    else
      # Last resort: write to temp file, print path
      TMP=$(mktemp /tmp/zellij-clip-XXXXXX)
      cat > "$TMP"
      echo "Clipboard data written to $TMP" >&2
    fi
  '';

  # ── Noctalia Color Sync Script ──────────────────────────────────────
  zellij-colors-sync = pkgs.writeShellScriptBin "zellij-colors-sync" ''
        COLORS_FILE="''${HOME}/.config/hypr/noctalia/noctalia-colors.conf"
        LUA_COLORS_FILE="''${HOME}/.config/hypr/noctalia/noctalia-colors.lua"
        LAYOUTS_DIR="''${HOME}/.config/zellij/layouts"
        mkdir -p "$LAYOUTS_DIR"

        PRIMARY="00e468"; SECONDARY="84d990"; SURFACE="0d150d"; TERTIARY="51d5ff"; ERROR="ffb4ab"

        # Helper: extract hex color from rgb(...) format
        extract_hex() { sed 's/.*rgb(\([a-f0-9]*\)).*/\1/' | tr -d $'\r\n'; }

        if [ -s "$COLORS_FILE" ]; then
          PRIMARY=$(grep '^\$primary[[:space:]]' "$COLORS_FILE" | extract_hex)
          SECONDARY=$(grep '^\$secondary[[:space:]]' "$COLORS_FILE" | extract_hex)
          SURFACE=$(grep '^\$surface[[:space:]]' "$COLORS_FILE" | extract_hex)
          TERTIARY=$(grep '^\$tertiary[[:space:]]' "$COLORS_FILE" | extract_hex)
          ERROR=$(grep '^\$error[[:space:]]' "$COLORS_FILE" | extract_hex)
          # Restore defaults if grep found nothing
          [ -z "$PRIMARY" ] && PRIMARY="00e468"
          [ -z "$SECONDARY" ] && SECONDARY="84d990"
          [ -z "$SURFACE" ] && SURFACE="0d150d"
          [ -z "$TERTIARY" ] && TERTIARY="51d5ff"
          [ -z "$ERROR" ] && ERROR="ffb4ab"
        elif [ -s "$LUA_COLORS_FILE" ]; then
          # Fallback: parse colors from noctalia-colors.lua (generated by noctalia directly)
          LUA_PRIMARY=$(grep 'local primary' "$LUA_COLORS_FILE" | extract_hex)
          LUA_SURFACE=$(grep 'local surface' "$LUA_COLORS_FILE" | head -1 | extract_hex)
          LUA_SECONDARY=$(grep 'local secondary' "$LUA_COLORS_FILE" | extract_hex)
          LUA_ERROR=$(grep 'local error' "$LUA_COLORS_FILE" | extract_hex)
          [ -n "$LUA_PRIMARY" ] && PRIMARY="$LUA_PRIMARY"
          [ -n "$LUA_SURFACE" ] && SURFACE="$LUA_SURFACE"
          [ -n "$LUA_SECONDARY" ] && SECONDARY="$LUA_SECONDARY"
          [ -n "$LUA_ERROR" ] && ERROR="$LUA_ERROR"
        fi

        ZJSTATUS_WASM="${zjstatusWasm}"

        gen_bar() {
          cat <<KDL
            pane size=1 borderless=true {
                plugin location="file:''${ZJSTATUS_WASM}" {
                  format_left   "#[fg=#''${SECONDARY},bold] {session} #[fg=#6c7086] {mode}"
                  format_center "#[fg=#9399b2] {tabs}"
                  format_right  "#[fg=#6c7086] {command_git_branch} #[fg=#''${PRIMARY}] {command_hostname} #[fg=#6c7086] {datetime}"
                  format_space  ""

                  border_enabled  "false"
                  hide_frame_for_single_pane "false"

                  mode_normal  "#[bg=#''${PRIMARY},fg=#''${SURFACE},bold] NORMAL "
                  mode_resize  "#[bg=#f9e2af,fg=#''${SURFACE},bold] RESIZE "
                  mode_scroll  "#[bg=#89b4fa,fg=#''${SURFACE},bold] SCROLL "
                  mode_session "#[bg=#cba6f7,fg=#''${SURFACE},bold] SESSION "
                  mode_tmux    "#[bg=#''${ERROR},fg=#''${SURFACE},bold] TMUX "

                  tab_normal   "#[fg=#6c7086] {name} #[fg=default]"
                  tab_active   "#[bg=#''${PRIMARY},fg=#''${SURFACE},bold] {name} #[bg=default,fg=#''${PRIMARY}]"

                  command_hostname_command     "hostname"
                  command_hostname_format      " {stdout} "
                  command_hostname_interval    "60"
                  command_hostname_rendermode  "static"

                  command_git_branch_command     "git rev-parse --abbrev-ref HEAD 2>/dev/null"
                  command_git_branch_format      "#[fg=#''${SECONDARY}]  {stdout}"
                  command_git_branch_interval    "10"
                  command_git_branch_rendermode  "static"
                  command_git_branch_cwd         "{focused_pane_cwd}"

                  datetime        "#[fg=#6c7086]  {format} "
                  datetime_format "%a %d %b %H:%M"
                  datetime_timezone "America/Los_Angeles"
                }
              }
              children
    KDL
        }

        gen_bottom_bar() {
          cat <<KDL
              pane size=1 borderless=true {
                plugin location="file:''${ZJSTATUS_WASM}" {
                  format_left   "#[fg=#''${SECONDARY}] {command_cpu}"
                  format_center ""
                  format_right  "#[fg=#''${TERTIARY}] {command_ram}"
                  format_space  ""
                  border_enabled  "false"
                  hide_frame_for_single_pane "false"

                  command_cpu_command     "top -bn1 | grep 'Cpu' | tail -1 | awk '{printf \"cpu %.0f%%\", 100-\$8}'"
                  command_cpu_format      " {stdout} "
                  command_cpu_interval    "5"
                  command_cpu_rendermode  "static"

                  command_ram_command     "free -h | awk '/^Mem:/ {printf \"mem %s/%s\", \$3, \$2}'"
                  command_ram_format      " {stdout} "
                  command_ram_interval    "5"
                  command_ram_rendermode  "static"
                }
              }
    KDL
        }

        BAR=$(gen_bar)
        BOTTOM_BAR=$(gen_bottom_bar)

        # ── Generate Noctalia-synced Zellij theme ──
        hex_to_rgb() {
          local h="$1"
          echo "$((0x''${h:0:2})) $((0x''${h:2:2})) $((0x''${h:4:4}))"
        }
        PR=$(hex_to_rgb "$PRIMARY")
        SE=$(hex_to_rgb "$SECONDARY")
        SU=$(hex_to_rgb "$SURFACE")
        TE=$(hex_to_rgb "$TERTIARY")
        ER=$(hex_to_rgb "$ERROR")

        THEMES_DIR="''${HOME}/.config/zellij/themes"
        mkdir -p "$THEMES_DIR"

        cat > "$THEMES_DIR/noctalia.kdl" <<KDL
        themes {
            noctalia {
                ribbon_unselected {
                    base 192 192 192
                    background ''${SU}
                    emphasis_0 ''${TE}
                    emphasis_1 ''${SE}
                    emphasis_2 ''${PR}
                    emphasis_3 ''${ER}
                }
                ribbon_selected {
                    base ''${SU}
                    background ''${PR}
                    emphasis_0 ''${TE}
                    emphasis_1 ''${SE}
                    emphasis_2 ''${PR}
                    emphasis_3 ''${ER}
                }
                text_unselected {
                    base 192 192 192
                    background ''${SU}
                    emphasis_0 ''${TE}
                    emphasis_1 ''${SE}
                    emphasis_2 ''${PR}
                    emphasis_3 ''${ER}
                }
                text_selected {
                    base 192 192 192
                    background ''${SU}
                    emphasis_0 ''${TE}
                    emphasis_1 ''${SE}
                    emphasis_2 ''${PR}
                    emphasis_3 ''${ER}
                }
                frame_unselected {
                    base 192 192 192
                    background ''${SU}
                    emphasis_0 ''${TE}
                    emphasis_1 ''${SE}
                    emphasis_2 ''${PR}
                    emphasis_3 ''${ER}
                }
                frame_selected {
                    base ''${PR}
                    background ''${SU}
                    emphasis_0 ''${TE}
                    emphasis_1 ''${SE}
                    emphasis_2 ''${PR}
                    emphasis_3 ''${ER}
                }
                frame_highlight {
                    base ''${TE}
                    background ''${SU}
                    emphasis_0 ''${TE}
                    emphasis_1 ''${SE}
                    emphasis_2 ''${PR}
                    emphasis_3 ''${ER}
                }
            }
        }
        theme "noctalia"
    KDL

        # Write atomically — write to temp, then rename so zellij never sees a missing layout
        _tmp_opencode=$(mktemp "$LAYOUTS_DIR/opencode.kdl.tmp.XXXXXX")
        _tmp_compact=$(mktemp "$LAYOUTS_DIR/compact.kdl.tmp.XXXXXX")

        cat > "$_tmp_opencode" <<KDL
          layout {
            default_tab_template {
              ''${BAR}
              ''${BOTTOM_BAR}
            }
            tab name="opencode" {
              pane split_direction="vertical" {
                pane size="70%" {
                  command "opencode"
                }
                pane {
                  pane split_direction="horizontal" {
                    pane size="50%" {
                      command "zsh"
                    }
                    pane size="50%" {
                      command "zsh"
                    }
                  }
                }
              }
            }
            tab name="hermes" {
              pane {
                command "hermes"
                args "--tui"
              }
            }
            tab name="ide" {
              pane split_direction="vertical" {
                pane size="25%" {
                  command "yazi"
                }
                pane size="75%" {
                  command "nvim"
                }
              }
            }
            tab name="shell" {
              pane {
                cwd "/home/t0psh31f/Clan/NFP"
                command "zsh"
              }
            }
          }
    KDL

        cat > "$_tmp_compact" <<KDL
          layout {
            pane {
              command "zsh"
            }
          }
    KDL

        # Atomic rename so zellij never sees a missing/incomplete layout file
        mv "$_tmp_opencode" "$LAYOUTS_DIR/opencode.kdl"
        mv "$_tmp_compact" "$LAYOUTS_DIR/compact.kdl"

        echo "zjstatus synced (primary=#''${PRIMARY})"
  '';

  # ── zjstatus plugin reference ──────────────────────────────────────
  zjstatusPlugin = ''plugin location="file:${zjstatusWasm}"'';

  # ── Bottom bar (CPU + RAM) — gated on yazelix bars flag ─────────────
  bottomBarPane = lib.optionalString cfg.zellij.yazelix.bars.enable ''
    pane size=1 borderless=true {
      ${zjstatusPlugin} {
        format_left   "#[fg=#f9e2af] {command_cpu}"
        format_center ""
        format_right  "#[fg=#89b4fa] {command_ram}"
        format_space  ""
        border_enabled  "false"
        hide_frame_for_single_pane "false"

        command_cpu_command     "top -bn1 | grep 'Cpu' | tail -1 | awk '{printf \"cpu %.0f%%\", 100-\$8}'"
        command_cpu_format      " {stdout} "
        command_cpu_interval    "5"
        command_cpu_rendermode  "static"

        command_ram_command     "free -h | awk '/^Mem:/ {printf \"mem %s/%s\", \$3, \$2}'"
        command_ram_format      " {stdout} "
        command_ram_interval    "5"
        command_ram_rendermode  "static"
      }
    }
  '';

  # ── Layouts ────────────────────────────────────────────────────────
  layouts = {
    opencode = ''
            layout {
              default_tab_template {
                pane size=1 borderless=true {
                  ${zjstatusPlugin} {
                    format_left   "#[fg=#84d990,bold] {session} #[fg=#6c7086] {mode}"
                    format_center "#[fg=#9399b2] {tabs}"
                    format_right  "#[fg=#6c7086] {command_git_branch} #[fg=#00e468] {command_hostname} #[fg=#6c7086] {datetime}"
                    format_space  ""

                    border_enabled  "false"
                    hide_frame_for_single_pane "false"

                    mode_normal  "#[bg=#00e468,fg=#0d150d,bold] NORMAL "
                    mode_resize  "#[bg=#f9e2af,fg=#0d150d,bold] RESIZE "
                    mode_scroll  "#[bg=#89b4fa,fg=#0d150d,bold] SCROLL "
                    mode_session "#[bg=#cba6f7,fg=#0d150d,bold] SESSION "
                    mode_tmux    "#[bg=#f38ba8,fg=#0d150d,bold] TMUX "

                    tab_normal   "#[fg=#6c7086] {name} #[fg=default]"
                    tab_active   "#[bg=#00e468,fg=#0d150d,bold] {name} #[bg=default,fg=#00e468]"

                    command_hostname_command     "hostname"
                    command_hostname_format      " {stdout} "
                    command_hostname_interval    "60"
                    command_hostname_rendermode  "static"

                    command_git_branch_command     "git rev-parse --abbrev-ref HEAD 2>/dev/null"
                    command_git_branch_format      "#[fg=#84d990]  {stdout}"
                    command_git_branch_interval    "10"
                    command_git_branch_rendermode  "static"
                    command_git_branch_cwd         "{focused_pane_cwd}"

                    datetime        "#[fg=#6c7086]  {format} "
                    datetime_format "%a %d %b %H:%M"
                    datetime_timezone "America/Los_Angeles"
                  }
                }
                children
      ${bottomBarPane}
              }
              tab name="opencode" {
                pane split_direction="vertical" {
                  pane size="70%" {
                    command "opencode"
                  }
                  pane {
                    pane split_direction="horizontal" {
                      pane size="50%" {
                        command "zsh"
                      }
                      pane size="50%" {
                        command "zsh"
                      }
                    }
                  }
                }
              }
              tab name="hermes" {
                pane {
                  command "hermes"
                  args "--tui"
                }
              }
              tab name="ide" {
                pane split_direction="vertical" {
                  pane size="25%" {
                    command "yazi"
                  }
                  pane size="75%" {
                    command "nvim"
                  }
                }
              }
              tab name="shell" {
                pane {
                  cwd "/home/t0psh31f/Clan/NFP"
                  command "zsh"
                }
              }
            }
    '';

    compact = ''
      layout {
        pane {
          command "zsh"
        }
      }
    '';

    dev = ''
            layout {
              default_tab_template {
                pane size=1 borderless=true {
                  ${zjstatusPlugin} {
                    format_left   "{mode} #[fg=#9399b2,bold]{session}"
                    format_center "{tabs}"
                    format_right  "#[fg=#6c7086]{command_git_branch} #[fg=#9399b2,bold]{datetime}"
                    format_space  ""

                    border_enabled  "false"
                    hide_frame_for_single_pane "false"

                    mode_normal  "#[bg=#4ce33b,fg=#0d150b,bold] NORMAL "
                    mode_resize  "#[bg=#f9e2af,fg=#0d150b,bold] RESIZE "
                    mode_scroll  "#[bg=#89b4fa,fg=#0d150b,bold] SCROLL "
                    mode_session "#[bg=#cba6f7,fg=#0d150b,bold] SESSION "
                    mode_tmux    "#[bg=#ffb4ab,fg=#0d150b,bold] TMUX "

                    tab_normal   "#[fg=#6c7086] {name} "
                    tab_active   "#[fg=#4ce33b,bold,italic] {name} "

                    command_git_branch_command     "git rev-parse --abbrev-ref HEAD 2>/dev/null"
                    command_git_branch_format      "#[fg=#8ada77]  {stdout}"
                    command_git_branch_interval    "10"
                    command_git_branch_rendermode  "static"
                    command_git_branch_cwd         "{focused_pane_cwd}"

                    datetime        "#[fg=#6c7086]  {format} "
                    datetime_format "%a %d %b %H:%M"
                    datetime_timezone "America/Chicago"
                  }
                }
                children
      ${bottomBarPane}
              }
              tab name="dev" {
                pane split_direction="vertical" {
                  pane size="70%" {
                    command "nvim"
                  }
                  pane size="30%" {
                    command "lazygit"
                  }
                }
              }
              tab name="shell" {
                pane {
                  command "zsh"
                }
              }
              tab name="files" {
                pane {
                  command "yazi"
                }
              }
            }
    '';

    git = ''
            layout {
              default_tab_template {
                pane size=1 borderless=true {
                  ${zjstatusPlugin} {
                    format_left   "{mode} #[fg=#9399b2,bold]{session}"
                    format_center "{tabs}"
                    format_right  "#[fg=#6c7086]{command_git_branch} #[fg=#9399b2,bold]{datetime}"
                    format_space  ""

                    border_enabled  "false"
                    hide_frame_for_single_pane "false"

                    mode_normal  "#[bg=#4ce33b,fg=#0d150b,bold] NORMAL "
                    mode_resize  "#[bg=#f9e2af,fg=#0d150b,bold] RESIZE "
                    mode_scroll  "#[bg=#89b4fa,fg=#0d150b,bold] SCROLL "
                    mode_session "#[bg=#cba6f7,fg=#0d150b,bold] SESSION "
                    mode_tmux    "#[bg=#ffb4ab,fg=#0d150b,bold] TMUX "

                    tab_normal   "#[fg=#6c7086] {name} "
                    tab_active   "#[fg=#4ce33b,bold,italic] {name} "

                    command_git_branch_command     "git rev-parse --abbrev-ref HEAD 2>/dev/null"
                    command_git_branch_format      "#[fg=#8ada77]  {stdout}"
                    command_git_branch_interval    "10"
                    command_git_branch_rendermode  "static"
                    command_git_branch_cwd         "{focused_pane_cwd}"

                    datetime        "#[fg=#6c7086]  {format} "
                    datetime_format "%a %d %b %H:%M"
                    datetime_timezone "America/Chicago"
                  }
                }
                children
      ${bottomBarPane}
              }
              tab name="git" {
                pane {
                  command "lazygit"
                }
              }
              tab name="shell" {
                pane {
                  command "zsh"
                }
              }
            }
    '';

    server = ''
            layout {
              default_tab_template {
                pane size=1 borderless=true {
                  ${zjstatusPlugin} {
                    format_left   "{mode} #[fg=#9399b2,bold]{session}"
                    format_center "{tabs}"
                    format_right  "#[fg=#6c7086]{command_git_branch} #[fg=#9399b2,bold]{datetime}"
                    format_space  ""

                    border_enabled  "false"
                    hide_frame_for_single_pane "false"

                    mode_normal  "#[bg=#4ce33b,fg=#0d150b,bold] NORMAL "
                    mode_resize  "#[bg=#f9e2af,fg=#0d150b,bold] RESIZE "
                    mode_scroll  "#[bg=#89b4fa,fg=#0d150b,bold] SCROLL "
                    mode_session "#[bg=#cba6f7,fg=#0d150b,bold] SESSION "
                    mode_tmux    "#[bg=#ffb4ab,fg=#0d150b,bold] TMUX "

                    tab_normal   "#[fg=#6c7086] {name} "
                    tab_active   "#[fg=#4ce33b,bold,italic] {name} "

                    command_git_branch_command     "git rev-parse --abbrev-ref HEAD 2>/dev/null"
                    command_git_branch_format      "#[fg=#8ada77]  {stdout}"
                    command_git_branch_interval    "10"
                    command_git_branch_rendermode  "static"
                    command_git_branch_cwd         "{focused_pane_cwd}"

                    datetime        "#[fg=#6c7086]  {format} "
                    datetime_format "%a %d %b %H:%M"
                    datetime_timezone "America/Chicago"
                  }
                }
                children
      ${bottomBarPane}
              }
              tab name="monitor" {
                pane split_direction="vertical" {
                  pane size="50%" {
                    command "htop"
                  }
                  pane size="50%" {
                    command "journalctl" {
                      args "-f"
                    }
                  }
                }
              }
              tab name="shell" {
                pane {
                  command "zsh"
                }
              }
            }
    '';
  };

in
{
  home = lib.mkIf (cfg.enable && cfg.zellij.enable) {
    programs.zellij = {
      enable = true;
      enableZshIntegration = false;

      settings = {
        pane_frames = false;
        default_layout = "opencode";
        simplified_ui = false;
        scrollback_buffer_size = 50000;
        scrollback_editor = editorBin;
        mouse_mode = true;
        copy_command = "zellij-clipboard";
        default_shell = "${pkgs.zsh}/bin/zsh";
        auto_copy_on_select = true;
        theme = "noctalia";
        session_serialization = true;
        pane_viewport_serialization = true;
      };

      extraConfig =
        lib.mkIf (cfg.zellij.yazelix.orchestrator.enable || cfg.zellij.yazelix.popup.enable)
          ''
            plugins {
              ${lib.optionalString cfg.zellij.yazelix.orchestrator.enable ''
                yazelix-pane-orchestrator location="file:${yazelixOrchestrator}/share/yazelix_pane_orchestrator.wasm" {
                    screen_saver_enabled false
                }
              ''}
              ${lib.optionalString cfg.zellij.yazelix.popup.enable ''
                yzpp location="file:${yazelixPopup}/share/yazelix_popup_runner.wasm" {
                    popup_defaults {
                        side_margin 1
                        vertical_margin 0
                    }
                    popup {
                        command "yazi"
                        pane_title "yazi_popup"
                        command_marker "yazi"
                        cwd "."
                        width_percent 90
                        height_percent 85
                    }
                }
              ''}
            }
            load_plugins {
              ${lib.optionalString cfg.zellij.yazelix.orchestrator.enable "yazelix-pane-orchestrator"}
              ${lib.optionalString cfg.zellij.yazelix.popup.enable "yzpp"}
            }
            ${lib.optionalString (cfg.zellij.yazelix.orchestrator.enable || cfg.zellij.yazelix.popup.enable) ''
              keybinds {
                  normal {
            ''}
            ${lib.optionalString cfg.zellij.yazelix.orchestrator.enable ''
              bind "Alt y" {
                  MessagePlugin "yazelix-pane-orchestrator" {
                      name "toggle_sidebar"
                  }
              }
            ''}
            ${lib.optionalString cfg.zellij.yazelix.popup.enable ''
              bind "Alt g" {
                  MessagePlugin "yzpp" {
                      name "toggle"
                  }
              }
            ''}
            ${lib.optionalString (cfg.zellij.yazelix.orchestrator.enable || cfg.zellij.yazelix.popup.enable) ''
                  }
              }
            ''}
          '';
    };

    xdg.configFile = lib.mapAttrs' (name: kdl: {
      name = "zellij/layouts/${name}.kdl";
      value = {
        text = kdl;
      };
    }) layouts;

    programs.zsh.initContent = lib.mkBefore ''
      # Sync zjstatus layouts with Noctalia colors BEFORE zellij auto-init
      if command -v zellij-colors-sync >/dev/null 2>&1; then
        zellij-colors-sync 2>/dev/null || true
      fi
    '';

    systemd.user.services.zellij-colors = {
      Unit = {
        Description = "Sync zjstatus layouts with Noctalia colors";
        After = [ "graphical-session.target" ];
      };
      Service = {
        Type = "oneshot";
        ExecStart = "${zellij-colors-sync}/bin/zellij-colors-sync";
      };
      Install = {
        WantedBy = [ "graphical-session.target" ];
      };
    };

    home.packages = [
      zellij-colors-sync
      zellij-clipboard
    ];
  };
}
