# Hardware Configuration Placeholder
#
# This file should be generated by nixos-generate-config:
#   nixos-generate-config --root /mnt --show-hardware-config > hardware-configuration.nix
#
# Or use clan's facter for automatic hardware detection:
#   clan facts generate <machine-name>
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];

  # This is a placeholder. Replace with actual hardware configuration!
  # Key things to configure:
  # - boot.initrd.availableKernelModules
  # - boot.initrd.kernelModules
  # - boot.kernelModules
  # - fileSystems
  # - swapDevices
  # - nixpkgs.hostPlatform

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  nixpkgs.hostPlatform = "x86_64-linux";
}
